-- VHDL Entity PPI_zad3_detektor_101_lib.detektor101_tb.symbol
--
-- Created:
--          by - marek.UNKNOWN (LAPTOP-32238)
--          at - 18:01:26 14. 12. 2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--


ENTITY detektor101_tb IS
-- Declarations

END detektor101_tb ;

--
-- VHDL Architecture PPI_zad3_detektor_101_lib.detektor101_tb.struct
--
-- Created:
--          by - marek.UNKNOWN (LAPTOP-32238)
--          at - 18:01:26 14. 12. 2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

LIBRARY PPI_zad3_detektor_101_lib;

ARCHITECTURE struct OF detektor101_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL X     : std_logic;
   SIGNAL Y     : std_logic;
   SIGNAL Y_fsm : std_logic;
   SIGNAL clk   : std_logic;
   SIGNAL rst   : std_logic;


   -- Component Declarations
   COMPONENT FSM_Moore
   PORT (
      X     : IN     std_logic ;
      clk   : IN     std_logic ;
      rst   : IN     std_logic ;
      Y_fsm : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT detektor101
   PORT (
      X   : IN     std_logic ;
      clk : IN     std_logic ;
      clr : IN     std_logic ;
      Y   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT detektor101_tester
   PORT (
      X   : OUT    std_logic ;
      clk : OUT    std_logic ;
      rst : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FSM_Moore USE ENTITY PPI_zad3_detektor_101_lib.FSM_Moore;
   FOR ALL : detektor101 USE ENTITY PPI_zad3_detektor_101_lib.detektor101;
   FOR ALL : detektor101_tester USE ENTITY PPI_zad3_detektor_101_lib.detektor101_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : FSM_Moore
      PORT MAP (
         X     => X,
         clk   => clk,
         rst   => rst,
         Y_fsm => Y_fsm
      );
   U_0 : detektor101
      PORT MAP (
         X   => X,
         clk => clk,
         clr => rst,
         Y   => Y
      );
   U_1 : detektor101_tester
      PORT MAP (
         X   => X,
         clk => clk,
         rst => rst
      );

END struct;
