-- VHDL Entity PPI_zad3_detektor_101_lib.detektor101_tester.interface
--
-- Created:
--          by - marek.UNKNOWN (LAPTOP-32238)
--          at - 19:18:38 12. 12. 2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

ENTITY detektor101_tester IS
   PORT( 
      X   : OUT    std_logic;
      clk : OUT    std_logic;
      rst : OUT    std_logic
   );

-- Declarations

END detektor101_tester ;

--
-- VHDL Architecture PPI_zad3_detektor_101_lib.detektor101_tester.flow
--
-- Created:
--          by - marek.UNKNOWN (LAPTOP-32238)
--          at - 19:18:38 12. 12. 2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;
ARCHITECTURE flow OF detektor101_tester IS

BEGIN

   -----------------------------------------------------------------
   process0_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      X <= '1';
      wait for 50 ns;
      X <= '1';
      wait for 50 ns;
      X <= '1';
      wait for 50 ns;
      X <= '0';
      wait for 50 ns;
      X <= '1';
      wait for 50 ns;
      X <= '0';
      wait for 50 ns;
   END PROCESS process0_proc;

   -----------------------------------------------------------------
   process1_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      rst <= '0';
      wait for 10 ns;
      rst <= '1';
      wait for 940 ns;
   END PROCESS process1_proc;

   -----------------------------------------------------------------
   process2_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      clk <= '0';
      wait for 25 ns;
      clk <= '1';
      wait for 25 ns;
   END PROCESS process2_proc;


END flow;
